import React from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className="bg-dark d-flex flex-column justify-content-between align-items-center min-vh-100">
        {children}
      </body>
    </html>
  );
}
